title: NEATO Winterfest
preposition: ''
description: >-
  Wintertime conference for Volunteers and Staff from North Eastern Trolley Organizations (NEATO). The conference is happening March 15, 16, and 17, 2024 at the Seashore Trolley Museum in Kennebunk, ME. A special tour of The National Streetcar Museum in Lowell, MA will happen on Friday, March 15.
baseurl: ""
url: "https://www.neatowinterfest.org"

plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

include:
  - '_past'

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:

  info_bars:
    #- title: Event has ended
    #  color: primary
    #  main_only: false
    #  text: |
    #    Winterfest 2024 has ended.
    #    ---
    #    We look forward to seeing you at Winterfest 2025!

  lang: en
  show_errors: True

  link_preview:
    disable: false

  speakers:
    show_firstname: true

  location:
    url: '/location'
    map: true
    navbar_title: 'Location'
    hide: false

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true

  map:
    # https://www.google.com/maps/place/Seashore+Trolley+Museum/@43.4091118,-70.4919693,17z/data=!3m1!4b1!4m6!3m5!1s0x4cb2aee9ad8bbb4d:0x92c1bd47775e8139!8m2!3d43.4091118!4d-70.4893944!16zL20vMDYyN2Z5?entry=ttu
    default_zoom: 17
    home_coord: "43.41028,-70.49213"
    #geo:43.41028,-70.49213?z=17
    map_provider: "OpenStreetMap.Mapnik"

  talks:
    main_categories:
      - name: "Lightning Talks"
        color: "LightningTalks"
      - name: Workshops
        color: Workshops
      - name: "Sessions"
        color: "Sessions"
      - name: "Roundtable Discussions and Fireside Chats"
        color: "Roundtable"
      - name: "Meals"
        color: "Meals"
      - name: "Information"
        color: "Information"
      - name: "Hands-On"
        color: "HandsOn"
      - name: "Entertainment"
        color: "Entertainment"
      - name: "Community Activities"
        color: "CommunityActivities"
      - name: "Tours"
        color: "Tours"


  navigation:
    links:
      - name: Schedule
        relative_url: /program/
      - name: Tickets
        disabled: false
        relative_url: /tickets/
        #absolute_url: ""
      - name: Lodging
        relative_url: /lodging/
      - name: Location
        relative_url: /location/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: FAQ
        relative_url: /faq/
      - name: 5K
        relative_url: /talks/Winterfest-5K-Registration/
      - name: 'Discord'
        relative_url: /discord/
        icon: "/assets/icons/discord.svg"
        #classes: "fab fa-discord"

      - name: Past Events
        menu:
          #- name: 2024 (current)
          #  disabled: true
          #  relative_url: /
          - name: 2023
            relative_url: /2023/
          - name: 2020
            relative_url: /2020/
          - name: 2019
            relative_url: /2019/
          - name: 2018
            relative_url: /2018/
          - name: 2017
            relative_url: /2017/
          - name: 2016
            relative_url: /2016/
          - name: 2015
            relative_url: /2015/
          - name: 2014
            relative_url: /2014/
          - name: 2013
            relative_url: /2013/



